from django.core.exceptions import ValidationError
import re


def id_card_validation(value):
    pass
